version: "3.4"
services:
  ms-log:
    image: bakayarusama/ms-log:1.0.0
    container_name: ms-log
    
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - log=Debug
        - plateform=windows/amd64
    ports: 
      - 1818:8080
    
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ApplicationVersion: 1.0.0
      ConnectionStrings__Database: "Data Source=/app/Data/database.db"

    volumes:
      - C:\Users\brend\Source\Repos\brendanGiraudet\MS-log\ms-log\Data:/app/Data
      
    restart: always